name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      placeholder: One sentence description
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Mockups, screenshots, related links, etc.